/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-10-31 15:54:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FrmActualizarPelicula_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/J:/PROYECTO_LP2_CINEHOME/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CineHome/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1686695274433L));
    _jspx_dependants.put("/MenuPrincipal.jsp", Long.valueOf(1700325219446L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Cine Home</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Estilos/EstilosMenu.css\">\r\n");
      out.write("<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"sidebar close\">\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text logo\">\r\n");
      out.write("\r\n");
      out.write("<span class=\"name\">MENU</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<i class=\"bx bx-menu toggle\"></i>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"menu-bar\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"menu\">\r\n");
      out.write("\t\r\n");
      out.write("\t<li class=\"search-box\">\r\n");
      out.write("\t<i class=\"bx bx-search icon\"></i>\r\n");
      out.write("\t<input type=\"text\" placeholder=\"Buscar...\">\r\n");
      out.write("\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("\t<ul class=\"menu-links\">\r\n");
      out.write("\t\t<li class=\"nav\">\r\n");
      out.write("\t\t<a href=\"ControladorPelicula?action=ListadoPelicula\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-home-alt icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Venta de Entrada</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li >\r\n");
      out.write("\t\t<a href=\"ControladorPelicula?action=Listar\" class=\"nav\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-wallet icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Peliculas</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t<a href=\"ControladorDetalleBoleta?accion=Listado\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-wallet icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Reportes</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav\">\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"#\" id=\"mantenimiento-link\" onclick=\"toggleSubMenu()\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-wallet icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Mantenimiento</span>\t\t\t\r\n");
      out.write("\t\t\t<i class='bx bx-chevron-down arrow'></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<ul class=\"sub-menu\" id=\"sub-menu\">\r\n");
      out.write("\t\t<li class=\"nav\"><a href=\"ControladorEmpleado?accion=NuevoEmp\" class=\"menu-link\">\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Empleados</span>\t\t\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav\"><a href=\"ControladorUsuario?accion=Listado\" class=\"menu-link\">\r\n");
      out.write("\t\t<span class=\"text nav-text\">Login</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav\"><a href=\"FrmRegistrarPelicula.jsp\"  class=\"menu-link\">\r\n");
      out.write("\t\t<span class=\"text nav-text\">Peliculas</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t</ul >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"botton-content\">\r\n");
      out.write("<li class=\"\">\r\n");
      out.write("<a href=\"#\"> \r\n");
      out.write("\t<i class=\"bx bx-log-out icon\"></i>\r\n");
      out.write("\t<span class=\"text nav-text\">Salir</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"mode\">\r\n");
      out.write("\t<div class=\"sun-moon\">\r\n");
      out.write("\t<i class=\"bx bx-moon icon\"></i>\r\n");
      out.write("\t<i class=\"bx bx-sun icon\"></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<span class=\"mode-text text\">Modo Oscuro</span>\r\n");
      out.write("\t<div class=\"toggle-switch\">\r\n");
      out.write("\t<span class=\"switch\"></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/codigo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <!-- para bootstrap -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<section class=\"home\" id=\"content\">\r\n");
      out.write("<div class=\"container col-md-4\">\r\n");
      out.write("    <form action=\"ControladorPelicula\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <h1>Actualizar Nueva Película</h1>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"text-center mb-3\">\r\n");
      out.write("            <label>Nombres:</label>\r\n");
      out.write("            <input type=\"text\" value='");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("' name=\"nompelicula\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"text-center mb-3\">\r\n");
      out.write("            <label>Seleccionar un nueva imagen:</label>\r\n");
      out.write("            <input type=\"file\" name=\"fotopelicula\" id=\"file\" style=\"Display :none;\">\r\n");
      out.write("             <button id=\"customButton\" class=\"btn btn-danger\" type=\"button\">Seleccionar</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"selectedFileName\"></div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fotopelicula}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"imagen de la película\" id=\"img\" width=\"130px\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div>\r\n");
      out.write("            <input type=\"hidden\" value='");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("' name=\"idpelicula\">\r\n");
      out.write("            <input type=\"hidden\" value='");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("' name=\"fotopelicula\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("            <input type=\"submit\" name=\"action\" value=\"Actualizar\" class=\"btn btn-primary\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("            <a href=\"ControladorPelicula?action=Listar\" class=\"btn btn-warning\">Regresar al listado Películas</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("        const fileInput = document.getElementById(\"file\");\r\n");
      out.write("        const img = document.getElementById(\"img\");\r\n");
      out.write("\r\n");
      out.write("        fileInput.addEventListener(\"change\", function (e) {\r\n");
      out.write("            if (e.target.files[0]) {\r\n");
      out.write("                const reader = new FileReader();\r\n");
      out.write("                reader.onload = function (e) {\r\n");
      out.write("                    img.src = e.target.result;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                reader.readAsDataURL(e.target.files[0])\r\n");
      out.write("            } else {\r\n");
      out.write("                img.src = \"http://localhost/files/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fotopelicula}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; // Puedes poner una imagen por defecto\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Disparar el evento change para que la imagen se muestre al cargar la página\r\n");
      out.write("        fileInput.dispatchEvent(new Event(\"change\"));\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById('customButton').addEventListener('click', function () {\r\n");
      out.write("        document.getElementById('file').click();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /FrmActualizarPelicula.jsp(25,38) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nompelicula}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /FrmActualizarPelicula.jsp(40,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idpelicula}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent(null);
    // /FrmActualizarPelicula.jsp(41,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fotopelicula}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }
}
