/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-10-31 14:46:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FrmRegistrarPelicula_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/MenuPrincipal.jsp", Long.valueOf(1700325219446L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Cine Home</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Estilos/EstilosMenu.css\">\r\n");
      out.write("<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"sidebar close\">\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text logo\">\r\n");
      out.write("\r\n");
      out.write("<span class=\"name\">MENU</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<i class=\"bx bx-menu toggle\"></i>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"menu-bar\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"menu\">\r\n");
      out.write("\t\r\n");
      out.write("\t<li class=\"search-box\">\r\n");
      out.write("\t<i class=\"bx bx-search icon\"></i>\r\n");
      out.write("\t<input type=\"text\" placeholder=\"Buscar...\">\r\n");
      out.write("\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("\t<ul class=\"menu-links\">\r\n");
      out.write("\t\t<li class=\"nav\">\r\n");
      out.write("\t\t<a href=\"ControladorPelicula?action=ListadoPelicula\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-home-alt icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Venta de Entrada</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li >\r\n");
      out.write("\t\t<a href=\"ControladorPelicula?action=Listar\" class=\"nav\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-wallet icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Peliculas</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t<a href=\"ControladorDetalleBoleta?accion=Listado\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-wallet icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Reportes</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav\">\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"#\" id=\"mantenimiento-link\" onclick=\"toggleSubMenu()\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-wallet icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Mantenimiento</span>\t\t\t\r\n");
      out.write("\t\t\t<i class='bx bx-chevron-down arrow'></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<ul class=\"sub-menu\" id=\"sub-menu\">\r\n");
      out.write("\t\t<li class=\"nav\"><a href=\"ControladorEmpleado?accion=NuevoEmp\" class=\"menu-link\">\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Empleados</span>\t\t\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav\"><a href=\"ControladorUsuario?accion=Listado\" class=\"menu-link\">\r\n");
      out.write("\t\t<span class=\"text nav-text\">Login</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav\"><a href=\"FrmRegistrarPelicula.jsp\"  class=\"menu-link\">\r\n");
      out.write("\t\t<span class=\"text nav-text\">Peliculas</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t</ul >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"botton-content\">\r\n");
      out.write("<li class=\"\">\r\n");
      out.write("<a href=\"#\"> \r\n");
      out.write("\t<i class=\"bx bx-log-out icon\"></i>\r\n");
      out.write("\t<span class=\"text nav-text\">Salir</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"mode\">\r\n");
      out.write("\t<div class=\"sun-moon\">\r\n");
      out.write("\t<i class=\"bx bx-moon icon\"></i>\r\n");
      out.write("\t<i class=\"bx bx-sun icon\"></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<span class=\"mode-text text\">Modo Oscuro</span>\r\n");
      out.write("\t<div class=\"toggle-switch\">\r\n");
      out.write("\t<span class=\"switch\"></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/codigo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- para bootstrap 5 -->\r\n");
      out.write("\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<section class=\"home\" id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container col-md-4\">\r\n");
      out.write("<form action=\"ControladorPelicula\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t<h1>Registrar Nueva Pelicula</h1>\r\n");
      out.write("\t<hr>\r\n");
      out.write("<br>\r\n");
      out.write("\t<div class=\"text-center mb-3\">\r\n");
      out.write("\t<label>Nombres:</label>\r\n");
      out.write("\t<input type=\"text\" name=\"nompelicula\">\r\n");
      out.write("\t</div> \t\r\n");
      out.write("\t<div class=\"text-center mb-3\">\t\r\n");
      out.write("\t<input type=\"file\" name=\"fotopelicula\" id=\"file\">\r\n");
      out.write("\t<div class=\"text-center\t\">\r\n");
      out.write("\t<img src=\"http://localhost/files/imagenpeli.png\" alt=\"avatar\" id=\"img\" width = \"130px\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"text-center\">\r\n");
      out.write("\t<input type=\"submit\" name=\"action\" value=\"Grabar\">\r\n");
      out.write("\t<input type=\"submit\" name=\"action\" value=\"Regresar\">\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"text-center\t\">\r\n");
      out.write("\t<a href=\"ControladorPelicula?action=Listar\" class=\"btn btn-secondary\">Regresar al listado Peliculas</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/previewimg.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
