/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-10-31 15:42:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ListadoPelicula_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/J:/PROYECTO_LP2_CINEHOME/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CineHome/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1686695274433L));
    _jspx_dependants.put("/MenuPrincipal.jsp", Long.valueOf(1700325219446L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Cine Home</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Estilos/EstilosMenu.css\">\r\n");
      out.write("<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"sidebar close\">\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text logo\">\r\n");
      out.write("\r\n");
      out.write("<span class=\"name\">MENU</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<i class=\"bx bx-menu toggle\"></i>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"menu-bar\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"menu\">\r\n");
      out.write("\t\r\n");
      out.write("\t<li class=\"search-box\">\r\n");
      out.write("\t<i class=\"bx bx-search icon\"></i>\r\n");
      out.write("\t<input type=\"text\" placeholder=\"Buscar...\">\r\n");
      out.write("\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("\t<ul class=\"menu-links\">\r\n");
      out.write("\t\t<li class=\"nav\">\r\n");
      out.write("\t\t<a href=\"ControladorPelicula?action=ListadoPelicula\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-home-alt icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Venta de Entrada</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li >\r\n");
      out.write("\t\t<a href=\"ControladorPelicula?action=Listar\" class=\"nav\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-wallet icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Peliculas</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t<a href=\"ControladorDetalleBoleta?accion=Listado\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-wallet icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Reportes</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav\">\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"#\" id=\"mantenimiento-link\" onclick=\"toggleSubMenu()\">\r\n");
      out.write("\t\t\t<i class=\"bx bx-wallet icon\"></i>\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Mantenimiento</span>\t\t\t\r\n");
      out.write("\t\t\t<i class='bx bx-chevron-down arrow'></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<ul class=\"sub-menu\" id=\"sub-menu\">\r\n");
      out.write("\t\t<li class=\"nav\"><a href=\"ControladorEmpleado?accion=NuevoEmp\" class=\"menu-link\">\r\n");
      out.write("\t\t\t<span class=\"text nav-text\">Empleados</span>\t\t\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav\"><a href=\"ControladorUsuario?accion=Listado\" class=\"menu-link\">\r\n");
      out.write("\t\t<span class=\"text nav-text\">Login</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav\"><a href=\"FrmRegistrarPelicula.jsp\"  class=\"menu-link\">\r\n");
      out.write("\t\t<span class=\"text nav-text\">Peliculas</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t</ul >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"botton-content\">\r\n");
      out.write("<li class=\"\">\r\n");
      out.write("<a href=\"#\"> \r\n");
      out.write("\t<i class=\"bx bx-log-out icon\"></i>\r\n");
      out.write("\t<span class=\"text nav-text\">Salir</span>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li class=\"mode\">\r\n");
      out.write("\t<div class=\"sun-moon\">\r\n");
      out.write("\t<i class=\"bx bx-moon icon\"></i>\r\n");
      out.write("\t<i class=\"bx bx-sun icon\"></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<span class=\"mode-text text\">Modo Oscuro</span>\r\n");
      out.write("\t<div class=\"toggle-switch\">\r\n");
      out.write("\t<span class=\"switch\"></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/codigo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Listado de Peliculas</title>\r\n");
      out.write("<!--js Datatable -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://cdn.datatables.net/buttons/2.4.2/js/buttons.bootstrap5.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.datatables.net/buttons/2.4.2/js/buttons.colVis.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- css Datatable -->\r\n");
      out.write("\t<link href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"https://cdn.datatables.net/buttons/2.4.2/css/buttons.bootstrap5.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--ICONS DE BOOTSTRAP5 -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write("    .table th, .table td {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .center-table {\r\n");
      out.write("        margin-left: auto;\r\n");
      out.write("        margin-right: auto;\r\n");
      out.write("    }\r\n");
      out.write("    /* Estilo para los botones de DataTables */\r\n");
      out.write(".dataTables_wrapper .dt-buttons {\r\n");
      out.write("    margin-left: 300px; /* Ajusta este valor según sea necesario */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Estilo para el cuadro de búsqueda de DataTables */\r\n");
      out.write(".dataTables_wrapper .dataTables_filter input {\r\n");
      out.write("    margin-right: 350px; /* Ajusta este valor según sea necesario */\r\n");
      out.write("}\r\n");
      out.write("img {\r\n");
      out.write("margin :auto;\r\n");
      out.write("cursor: pointer;\r\n");
      out.write("transition:1s;\r\n");
      out.write("}\r\n");
      out.write(" img:hover {\r\n");
      out.write(" transform: scale(1.1);\r\n");
      out.write(" transition:1s;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write("  <section class=\"home\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<h1 style=\" margin-left:295px;\">Listado de Películas</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!-- \t<form class=\"form-inline mb-3\" style=\" margin-left:285px;\">\r\n");
      out.write("        <label for=\"codigoPelicula\">Buscar Pelicula</label>\r\n");
      out.write("        <div style=\"Display:flex;\">\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"txtbuscar\" style=\"width: 200px;\" />\r\n");
      out.write("        <input type=\"submit\" name=\"action\" value=\"Buscar\" class=\"btn btn-success\" />\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("    </form> \r\n");
      out.write("     <span class=\"mt-5\" style=\" margin-left:285px;\">Total de registros: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ListadoPeliculas.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> -->\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    <br>\r\n");
      out.write("\t<table id=\"table\" class=\"table table-warning table-hover table-striped-columns table-sm center-table\" style=\"width:50%; margin-left:300px;\" >\r\n");
      out.write("\t <thead>\r\n");
      out.write("\t<tr class=\"table-dark\">\r\n");
      out.write("\t<th style=\"text-align: center;\" >Codigo</th>\r\n");
      out.write("\t<th  style=\"text-align: center;\">Nombre Pelicula</th>\r\n");
      out.write("\t<th >Portada</th>\r\n");
      out.write("\t<th >Eliminar</th>\r\n");
      out.write("\t<th >Editar</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t </thead>\r\n");
      out.write("\t   <tbody>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("  \r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("\t\tnew DataTable('#table', {\r\n");
      out.write("\t\t\t    language: {\r\n");
      out.write("                \"lengthMenu\": \"Mostrar _MENU_ registros\",\r\n");
      out.write("                \"zeroRecords\": \"No se encontraron resultados\",\r\n");
      out.write("                \"info\": \"Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros\",\r\n");
      out.write("                \"infoEmpty\": \"Mostrando registros del 0 al 0 de un total de 0 registros\",\r\n");
      out.write("                \"infoFiltered\": \"(filtrado de un total de _MAX_ registros)\",\r\n");
      out.write("                \"sSearch\": \"Buscar:\",\r\n");
      out.write("                \"oPaginate\": {\r\n");
      out.write("                    \"sFirst\": \"Primero\",\r\n");
      out.write("                    \"sLast\":\"Último\",\r\n");
      out.write("                    \"sNext\":\"Siguiente\",\r\n");
      out.write("                    \"sPrevious\": \"Anterior\"\r\n");
      out.write("\t\t\t     },\r\n");
      out.write("\t\t\t     \"sProcessing\":\"Procesando...\",\r\n");
      out.write("            },\r\n");
      out.write("            dom: 'Bfrtilp',\r\n");
      out.write("            \r\n");
      out.write("            responsive: \"true\",\r\n");
      out.write("            lengthMenu: [\r\n");
      out.write("                [5, 10,25, -1],\r\n");
      out.write("                [5, 10,25, 'All']\r\n");
      out.write("            ],\r\n");
      out.write("\t\t\tbuttons: [\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t  \t\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t    extend: 'print',\r\n");
      out.write("\t\t\t    text: 'Imprimir <i class=\"bi bi-printer\"></i>',\r\n");
      out.write("\t\t\t    titleAttr: 'Imprimir',\r\n");
      out.write("\t\t\t    title: 'Listado de Peliculas', // Aquí puedes cambiar el título\r\n");
      out.write("\t\t\t    className: 'btn btn-info',\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    exportOptions: {\r\n");
      out.write("\t\t\t        columns: ':visible',\r\n");
      out.write("\t\t\t        format: {\r\n");
      out.write("\t\t\t            body: function (inner, coldex, rowdex) {\r\n");
      out.write("\t\t\t                if (inner.length <= 0) return inner;\r\n");
      out.write("\t\t\t                var el = $.parseHTML(inner);\r\n");
      out.write("\t\t\t                var result = '';\r\n");
      out.write("\t\t\t                $.each(el, function (index, item) {\r\n");
      out.write("\t\t\t                    if (item.nodeName == '#text') result = result + item.textContent;\r\n");
      out.write("\t\t\t                    else if (item.nodeName == 'SUP') result = result + item.outerHTML;\r\n");
      out.write("\t\t\t                    else if (item.nodeName == 'STRONG') result = result + item.outerHTML;\r\n");
      out.write("\t\t\t                    else if (item.nodeName == 'IMG') result = result + item.outerHTML;\r\n");
      out.write("\t\t\t                    else result = result + item.innerText;\r\n");
      out.write("\t\t\t                });\r\n");
      out.write("\t\t\t                return result;\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    customize: function (win) {\r\n");
      out.write("\t                $(win.document.body).find('table').addClass('display').css('font-size', '9px');\r\n");
      out.write("\t                $(win.document.body).find('tr:nth-child(odd) td').each(function(index){\r\n");
      out.write("\t                    $(this).css('background-color','#D0D0D0');\r\n");
      out.write("\t                });\r\n");
      out.write("\t                $(win.document.body).find('h1').css('text-align','center');\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("            ],\r\n");
      out.write("     \r\n");
      out.write("    } );\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /ListadoPelicula.jsp(106,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("peli");
    // /ListadoPelicula.jsp(106,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/ListadoPelicula.jsp(106,4) '${ListadoPeliculas}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${ListadoPeliculas}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <tr>\r\n");
          out.write("    <td style=\"text-align: center;\">");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("    <td  style=\"text-align: center;\">");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("    <td><img src=\"http://localhost/files/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${peli.fotopelicula}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=\"150px\" height=\"200px\" onclick=\"openFulImg(this.src)\" /></td>\r\n");
          out.write("    <td>\r\n");
          out.write("        <a href=\"ControladorPelicula?action=Eliminar&idpelicula=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${peli.idpelicula}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"eliminar\">\r\n");
          out.write("            <img src=\"imagenes/eliminar.png\" width=\"30px\" height=\"30px\">\r\n");
          out.write("            <input type=\"hidden\" id=\"idpelicula\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${peli.idpelicula}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("        </a>\r\n");
          out.write("    </td>\r\n");
          out.write("    <td>\r\n");
          out.write("        <a href=\"ControladorPelicula?action=Modificar&idpelicula=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${peli.idpelicula}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"modificar\">\r\n");
          out.write("            <img src=\"imagenes/actualizar.png\" width=\"50px\" height=\"40px\">\r\n");
          out.write("            <input type=\"hidden\" id=\"idpelicula\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${peli.idpelicula}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("        </a>\r\n");
          out.write("    </td>\r\n");
          out.write("</tr>\r\n");
          out.write("\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoPelicula.jsp(108,36) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${peli.idpelicula}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /ListadoPelicula.jsp(109,37) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${peli.nompelicula}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }
}
